'use client'
const advisory = {
    "Anemia Profile": {
        "Description": "Anemia is a medical condition characterized by a deficiency of red blood cells or hemoglobin in the blood. Red blood cells are responsible for carrying oxygen from the lungs to the rest of the body, and hemoglobin is the protein within red blood cells that binds to oxygen. When the body doesn't have enough red blood cells or hemoglobin, it can't transport oxygen effectively to tissues and organs, leading to symptoms such as fatigue, weakness, pale skin, shortness of breath, dizziness, and in severe cases, chest pain or irregular heartbeat.",
        "Tips": "To reduce anemia, focus on a balanced diet rich in iron, vitamin B12, and folate. Incorporate foods like lean meats, poultry, fish, beans, lentils, tofu, spinach, kale, fortified cereals, citrus fruits, and bell peppers into your meals. Avoid substances that inhibit iron absorption, such as caffeine and tannins found in tea and coffee. Cook with cast iron cookware, stay hydrated, and limit alcohol intake. Regular exercise can improve circulation and overall health. Work closely with your healthcare provider to develop a personalized treatment plan, which may include supplements and medications."
    },
    "Liver Profile": {
        "Description": "The liver is a vital organ responsible for numerous functions in the body, including detoxification, metabolism, and synthesis of proteins and enzymes. Liver health is crucial for overall well-being. Liver problems can manifest through symptoms such as jaundice, abdominal pain, swelling, fatigue, and nausea. Maintaining a healthy lifestyle, including a balanced diet low in saturated fats and alcohol, regular exercise, and avoiding toxins, can support liver function. Consult with a healthcare professional for personalized advice and monitoring.",
        "Tips": "To maintain liver health, prioritize a balanced diet rich in fruits, vegetables, lean proteins, and whole grains. Limit intake of processed foods, saturated fats, and sugary beverages. Drink alcohol in moderation or avoid it altogether. Stay hydrated by drinking plenty of water. Engage in regular exercise to promote overall health and support liver function. Avoid exposure to toxins and chemicals whenever possible. Consult with a healthcare provider for personalized recommendations and monitoring."
    },
    "Electrolytes Profile": {
        "Description": "Electrolytes are minerals in your body that have an electric charge. They play a crucial role in various bodily functions, including regulating nerve and muscle function, maintaining hydration levels, and balancing blood pH. Common electrolytes include sodium, potassium, calcium, magnesium, chloride, and phosphate. Imbalances in electrolytes can lead to symptoms such as muscle cramps, weakness, confusion, irregular heartbeat, and seizures. Maintaining proper electrolyte balance is essential for overall health.",
        "Tips": "To maintain electrolyte balance, consume a balanced diet rich in fruits, vegetables, whole grains, and lean proteins. Stay hydrated by drinking water throughout the day. Avoid excessive consumption of sugary beverages and processed foods, which can disrupt electrolyte levels. Monitor your intake of sodium, potassium, and other electrolytes, especially if you have specific health conditions or take medications that affect electrolyte balance. Consult with a healthcare provider for personalized recommendations and monitoring."
    },
    "Diabetes Profile": {
        "Description": "Diabetes is a chronic condition characterized by high blood sugar levels resulting from either inadequate insulin production or the body's inability to use insulin effectively. There are different types of diabetes, including type 1, type 2, and gestational diabetes. Symptoms may include frequent urination, increased thirst, unexplained weight loss, fatigue, blurred vision, and slow wound healing. Managing diabetes involves maintaining blood sugar levels within target ranges through a combination of medication, diet, exercise, and lifestyle changes.",
        "Tips": "To manage diabetes effectively, monitor blood sugar levels regularly and follow a balanced diet that includes whole grains, fruits, vegetables, lean proteins, and healthy fats. Limit intake of refined carbohydrates, sugary foods, and beverages that can spike blood sugar levels. Engage in regular physical activity to improve insulin sensitivity and overall health. Take medications as prescribed by your healthcare provider and attend regular check-ups to monitor your condition. Manage stress levels and prioritize adequate sleep to support overall well-being."
    },
    "Kidney Profile": {
        "Description": "The kidneys are essential organs responsible for filtering waste products, excess fluids, and toxins from the blood, regulating electrolyte levels, and producing hormones that control blood pressure and red blood cell production. Chronic kidney disease (CKD) is a common condition characterized by gradual loss of kidney function over time. Symptoms may include fatigue, swelling, changes in urination, nausea, and shortness of breath. Managing kidney health involves adopting a healthy lifestyle, monitoring blood pressure, and managing underlying conditions.",
        "Tips": "To support kidney health, maintain a balanced diet that includes fruits, vegetables, whole grains, lean proteins, and healthy fats. Limit sodium intake to help manage blood pressure and reduce strain on the kidneys. Stay hydrated by drinking plenty of water throughout the day. Avoid excessive consumption of alcohol and caffeine, which can affect kidney function. Monitor blood pressure regularly and take medications as prescribed by your healthcare provider. Quit smoking and manage underlying conditions such as diabetes and high blood pressure to reduce the risk of kidney damage."
    },
    "Minerals Profile": {
        "Description": "Minerals are essential nutrients that the body needs in small amounts to function properly. They play critical roles in various bodily functions, including bone health, nerve function, muscle contraction, and enzyme activity. Common minerals include calcium, magnesium, potassium, phosphorus, sodium, and zinc. Maintaining adequate mineral levels is crucial for overall health and well-being.",
        "Tips": "To ensure adequate mineral intake, consume a balanced diet rich in fruits, vegetables, whole grains, nuts, seeds, lean proteins, and dairy or dairy alternatives. Include a variety of foods to ensure you get a wide range of minerals. Consider taking supplements if you have specific deficiencies or dietary restrictions, but consult with a healthcare provider before starting any new supplements. Avoid excessive intake of salt, sugar, and processed foods, which can disrupt mineral balance. Stay hydrated and maintain a healthy lifestyle to support overall mineral absorption and utilization."
    },
    "Blood Count": {
        "Description": "Blood count tests, also known as complete blood count (CBC) tests, provide valuable information about the quantity and quality of various components in the blood. These components include red blood cells, white blood cells, and platelets. CBC tests are commonly used to diagnose and monitor a wide range of conditions, including anemia, infections, and blood disorders. The results of a CBC test can help healthcare providers assess overall health and identify any abnormalities that may require further investigation or treatment.",
        "Tips": "To maintain optimal blood count levels, focus on a balanced diet rich in essential nutrients, including iron, vitamin B12, and folate. Incorporate foods such as lean meats, poultry, fish, beans, lentils, leafy greens, fortified cereals, and citrus fruits into your meals. Stay hydrated by drinking plenty of water throughout the day. Engage in regular physical activity to support overall health and circulation. Avoid smoking and excessive alcohol consumption, which can negatively impact blood count levels. Follow your healthcare provider's recommendations for routine check-ups and screenings to monitor blood count levels and address any underlying health concerns."
    }
}

export default advisory